%% parameter setting

if     stnm == NAV;
    Trend_P = 0.030;
elseif stnm == SSE;
    Trend_P = 0.021;
elseif stnm == MIM;
    Trend_P = 0.029;
elseif stnm == HDM;
    Trend_P = 0.023;
elseif stnm == LTS;
    Trend_P = 0.023;
elseif stnm == SHF;
    Trend_P = 0.015;
elseif stnm == WRF;
    Trend_P = 0.020;
elseif stnm == SK;
    Trend_P = 0.021;
elseif stnm == HDC;
    Trend_P = 0.022;
elseif stnm == SSTW;
    Trend_P = 0.017;
elseif stnm == CJDT;
    Trend_P = 0.025;
elseif stnm == HDMB;
    Trend_P = 0.024;
elseif stnm == GSHS;
    Trend_P = 0.029;
elseif stnm == KGIN;
    Trend_P = 0.048;
elseif stnm == SSEP;
    Trend_P = 0.021;
elseif stnm == LGD;
    Trend_P = 0.05;
elseif stnm == LGE;
    Trend_P = 0.020;
elseif stnm == LGEP
    Trend_P = 0.020;
elseif stnm == DSIC
    Trend_P = 0.022;
elseif stnm == KIA;
    Trend_P = 0.025;
elseif stnm == SKH;
    Trend_P = 0.025;
elseif stnm == LGCP;
    Trend_P = 0.020;
elseif stnm == LGL;
    Trend_P = 0.025;
elseif stnm == HDD;
    Trend_P = 0.025;
elseif stnm == KDEX;
    Trend_P = 0.009;
elseif stnm == LDCH;
    Trend_P = 0.022;
elseif stnm == SSBR;
    Trend_P = 0.021;
elseif stnm == SEDP;
    Trend_P = 0.021;
elseif stnm == SSH;
    Trend_P = 0.021;
elseif stnm == KTRN;
    Trend_P = 0.033;
elseif stnm == HDE;
    Trend_P = 0.029;
elseif stnm == KCC;
    Trend_P = 0.022;
elseif stnm == DHM;
    Trend_P = 0.025;
elseif stnm == KHO;
    Trend_P = 0.024;
elseif stnm == GS;
    Trend_P = 0.024;
elseif stnm == HDCB;
    Trend_P = 0.024;
end

